### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 3131: invalid start byte

### ISSUE THREAD

**Issue by GrigorijSchleifer** [MIT-LCP/mimic-code#435]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.physionet.org/about/mimic/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=
    * Checked online common solutions: https://opendata.stackexchange.com/questions/tagged/mimic-iii

### Description
Hello MIMIC community, I am trying to extract patients data from the discharge notes who are on statins and use the code from [this](https://github.com/tamhok/statseps) repository. I get an **UnicodeDecodeError** when I execute the **proc_mimic_drugs.py** script. 

* what you have tried

I extracted the noteevents table with this query: 
```sql
COPY (select * from mimiciii.noteevents) TO '/Volumes/X/GIT/statseps/Discharge_summaries/discharge_notes.csv' WITH (FORMAT CSV, HEADER);
```
and executed the script with ```python proc_mimic_drugs.py```. After a couple of seconds I get the following error:
```
Using ALL notes from /Volumes/X/GIT/statseps/Discharge_summaries
Using drugs from /Volumes/X/GIT/statseps
[0, 7, 14]
[6, 13, 136]
Lengths: 7 7 123
['atorvastatin', 'fluvastatin', 'lovastatin', 'pravastatin', 'rosuvastatin', 'simvastatin', 'pitavastatin']
['cholestyramine', 'colesevelam', 'colfibrate', 'fenofibrate', 'gemfibrozil', 'ezetimibe', 'niacin']
['betamethasone', 'cortisone', 'dexamethasone', 'fludrocortisone', 'hydrocortisone', 'methylprednisolone', 'paramethasone', 'prednisolone', 'prednisone', 'triamcinolone', 'abatacerpt', 'alefacept', 'anakinra', 'atacicept', 'azathioprine', 'belatercept', 'bleomycin', 'chlorambicol', 'ciclosporine', 'cyclophosphamide', 'dactinomycin', 'daunorubicin', 'dimethyl fumarate', 'doxorubicin', 'epirubicin', 'etanercept', 'everolimus', 'fingolimod', 'fluorouracil', 'interferon beta', 'leflunomide', 'lenalidomide', 'mercaptopurine', 'methotrexate', 'mithramycin', 'mitomycin', 'mycophenolate', 'myriocin', 'plicamycin', 'pomalidomide', 'rilonacept', 'sirolimus', 'tacrolimus', 'teriflunomide', 'thalidomide', 'abrilumab', 'adalimumab', 'anifrolumab', 'antithymocyte globulin', 'apolizumab', 'aselizumab', 'atorolimumab', 'basiliximab', 'belimumab', 'benralizumab', 'brodalumab', 'canakinumab', 'cedelizumab', 'certolizumab pegol', 'daclizumab', 'dupilumab', 'eculizumab', 'efalizumab', 'eldelumab', 'epratuzumab', 'erlizumab', 'etrolizumab', 'fontolizumab', 'golimumab', 'inebilizumab', 'infliximab', 'itolizumab', 'ixekizumab', 'lampalizumab', 'lanadelumab', 'lerdelimumab', 'ligelizumab', 'lulizumab pegol', 'mavrilimumab', 'mepolizumab', 'mogamulizumab', 'morolimumab', 'muromonab', 'namilumab', 'natalizumab', 'nivolumab', 'ocrelizumab', 'ofatumumab', 'omalizumab', 'oxelumab', 'ozoralizumab', 'pascolizumab', 'pateclizumab', 'pexelizumab', 'pidilizumab', 'placulumab', 'plozalizumab', 'quilizumab', 'reslizumab', 'rituximab', 'rontalizumab', 'rovelizumab', 'ruplizumab', 'samalizumab', 'sarilumab', 'secukinumab', 'sifalimumab', 'siltuximab', 'siplizumab', 'tabalumab', 'talizumab', 'teplizumab', 'tezepelumab', 'tocilizumab', 'toralizumab', 'tregalizumab', 'ulocuplumab', 'ustekinumab', 'varlilumab', 'vatelizumab', 'vedolizumab', 'visilizumab', 'vobarilizumab']
[['atorvastatin', 'fluvastatin', 'lovastatin', 'pravastatin', 'rosuvastatin', 'simvastatin', 'pitavastatin'], ['cholestyramine', 'colesevelam', 'colfibrate', 'fenofibrate', 'gemfibrozil', 'ezetimibe', 'niacin'], ['betamethasone', 'cortisone', 'dexamethasone', 'fludrocortisone', 'hydrocortisone', 'methylprednisolone', 'paramethasone', 'prednisolone', 'prednisone', 'triamcinolone', 'abatacerpt', 'alefacept', 'anakinra', 'atacicept', 'azathioprine', 'belatercept', 'bleomycin', 'chlorambicol', 'ciclosporine', 'cyclophosphamide', 'dactinomycin', 'daunorubicin', 'dimethyl fumarate', 'doxorubicin', 'epirubicin', 'etanercept', 'everolimus', 'fingolimod', 'fluorouracil', 'interferon beta', 'leflunomide', 'lenalidomide', 'mercaptopurine', 'methotrexate', 'mithramycin', 'mitomycin', 'mycophenolate', 'myriocin', 'plicamycin', 'pomalidomide', 'rilonacept', 'sirolimus', 'tacrolimus', 'teriflunomide', 'thalidomide', 'abrilumab', 'adalimumab', 'anifrolumab', 'antithymocyte globulin', 'apolizumab', 'aselizumab', 'atorolimumab', 'basiliximab', 'belimumab', 'benralizumab', 'brodalumab', 'canakinumab', 'cedelizumab', 'certolizumab pegol', 'daclizumab', 'dupilumab', 'eculizumab', 'efalizumab', 'eldelumab', 'epratuzumab', 'erlizumab', 'etrolizumab', 'fontolizumab', 'golimumab', 'inebilizumab', 'infliximab', 'itolizumab', 'ixekizumab', 'lampalizumab', 'lanadelumab', 'lerdelimumab', 'ligelizumab', 'lulizumab pegol', 'mavrilimumab', 'mepolizumab', 'mogamulizumab', 'morolimumab', 'muromonab', 'namilumab', 'natalizumab', 'nivolumab', 'ocrelizumab', 'ofatumumab', 'omalizumab', 'oxelumab', 'ozoralizumab', 'pascolizumab', 'pateclizumab', 'pexelizumab', 'pidilizumab', 'placulumab', 'plozalizumab', 'quilizumab', 'reslizumab', 'rituximab', 'rontalizumab', 'rovelizumab', 'ruplizumab', 'samalizumab', 'sarilumab', 'secukinumab', 'sifalimumab', 'siltuximab', 'siplizumab', 'tabalumab', 'talizumab', 'teplizumab', 'tezepelumab', 'tocilizumab', 'toralizumab', 'tregalizumab', 'ulocuplumab', 'ustekinumab', 'varlilumab', 'vatelizumab', 'vedolizumab', 'visilizumab', 'vobarilizumab']]
[]
[]
0.. .DS_Store

Traceback (most recent call last):
  File "proc_mimic_drugs.py", line 290, in <module>
    main()
  File "proc_mimic_drugs.py", line 154, in main
    for note in reader:
  File "/anaconda3/lib/python3.6/csv.py", line 111, in __next__
    self.fieldnames
  File "/anaconda3/lib/python3.6/csv.py", line 98, in fieldnames
    self._fieldnames = next(self.reader)
  File "/anaconda3/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 3131: invalid start byte
```
My guess was that the noteevents csv file is not UTF-8 encoded, while the default encoding for my system is set to UTF-8, so I checked the file encoding with 

```
file -I discharge_notes.csv
```

and the output was that the csv is encoded with the **us-asci** charset. Even though the utf-8 is part of the us-asci encoding I tried to force encoding to utf-8 with 

```
iconv -f US-ASCII -t UTF-8 /Volumes/X/GIT/statseps/Discharge_summaries/discharge_notes.csv > /Volumes/X/GIT/statseps/Discharge_summaries/discharge_notes_utf-8.csv
```
but got the UnicodeDecodeError again.

Also when I run the ```psql \l``` command my terminal shows me that the encoding is correct.

```
mimic=# psql \l
                                                   List of databases
       Name        |       Owner       | Encoding |   Collate   |    Ctype    |            Access privileges            
-------------------+-------------------+----------+-------------+-------------+-----------------------------------------
 mimic             | postgres          | UTF8     | en_US.UTF-8 | en_US.UTF-8 | 
 postgres          | schleifergrigorij | UTF8     | en_US.UTF-8 | en_US.UTF-8 | 
 schleifergrigorij | schleifergrigorij | UTF8     | en_US.UTF-8 | en_US.UTF-8 | 
 template0         | schleifergrigorij | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =c/schleifergrigorij                   +
                   |                   |          |             |             | schleifergrigorij=CTc/schleifergrigorij
 template1         | schleifergrigorij | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =c/schleifergrigorij                   +
                   |                   |          |             |             | schleifergrigorij=CTc/schleifergrigorij
(5 rows)
```

I have python 3.6.4 installed and my anaconda version is 4.4.10 on a MacBook Pro laptop. 

Any ideas? 

Thank you!

**Comment by tompollard** [comment]
Please raise an issue on the repository associated with the code you are trying to run: https://github.com/tamhok/statseps

**Comment by GrigorijSchleifer** [comment]
Hi @tompollard thank you! I will address the issue in the tamhok repository.
